### ISSUE TITLE
v4.1.5 SSLMITM generates fake certs despite sites being on exceptionsitelist

### ISSUE THREAD

**Issue by xenadmin** [e2guardian/e2guardian#402] opened 2018-06-22 13:24 UTC
Hello,
I have a Debian 9 e2guardian 4.1.5 installation with SSLMITM ON where we have massive problems with Teamviewer. My guess is, that TeamViewer doesn't like the fake certs. If i turn of SSLMITM it starts working immediately. 
In my understanding URLs listed in exceptionsitelist shouldn't get spoofed and reach the client with their original cert. I have another e2guardian setup where this is the case. 
What could happen in e2guardian, that certs of sites listed on exceptionsitelist still get faked?

**Comment by forid786** [comment] 2018-06-27 14:11
Have you got the transparent proxy enabled?

Also to verify, you can add teamviewer.com to the exception list and then visit the site on a normal browser and check the cert and see if it is still being MITM'd. I believe I had issues in the past but after adding the exceptions, I haven't had any trouble.

As with all MITM proxies, you will end up with a lot of exceptions due to cert pinning.

**Comment by xenadmin** [comment] 2018-06-28 12:26
No, no transparent proxy. Proxy is distirbuted via wpad.dat or via manual setting in Internet Explorer settings. 

teamviewer.com is on the exceptionsitelist, that is the reason I logged the issue. It's cert is beeing fake although the domain is on the list.

**Comment by forid786** [comment] 2018-06-28 12:35
That's really strange, I've not come across this issue although I'm currently on V5.1.

Have you got multiple groups configured? What authentication are you using? Check to see if the exception is assigned to the group in which your client is in.

**Comment by xenadmin** [comment] 2018-06-28 12:51
Yes, 4 groups. I use NTLM Sign On via Squid. The access.log lists the exception, although always through the wrong group. This means, user is originally in Group2, but TeamViewer.com access always lists in Group1. So I put the exception in Group1&2. The Exception gets listed but the certificate is still a fake.

**Comment by forid786** [comment] 2018-06-28 13:05
The source of the problem is definitely in your setup here. I haven't used that setup myself so can't help you much further. Perhaps @fredbcode can assist.

**Comment by fredbcode** [comment] 2018-06-29 08:52
How did you see that "that certs of sites listed on exceptionsitelist still get faked" ? Are you sure that this is not another url related ?

**Comment by xenadmin** [comment] 2018-06-29 12:59
I made 5 Tests for you. 3 Wrong, 2 Right. With Screenshots and Log files. I hope this explains what I mean!

1=Default-Group
2=ProxyInternet
VERTRAUENSWÜRDIG means EXCEPTION in German

Test1 - Wrong
Test2 - Wrong
Test3 - Right
Test4 - Right
Test5 - Wrong

**Test 1 - www.google.de**
![grafik](https://user-images.githubusercontent.com/12057348/42093238-ee54824c-7bab-11e8-8574-1f357946549e.png)
Windows User Administrator, Member of Group2 ProxyInternet
Log Example:
`18.06.29 13:17:04 administrator 10.21.30.21 https://www.google.de - GET 200601 -115 - 2 200 text/html 10.21.30.21 ProxyInternet - - - - -`

**Test 2 - www.eset.com**
![grafik](https://user-images.githubusercontent.com/12057348/42093267-07e96f9c-7bac-11e8-95d7-18a2f98a4afe.png)
Windows User Administrator, Member of Group2 ProxyInternet
Log Example:
`18.06.29 13:19:21 - 10.21.30.21 https://www.eset.com *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste GET 7974 0 - 1 200 text/html 10.21.30.21 Default-Group - - - - -`

**Test 3 - www.oracle.com**
![grafik](https://user-images.githubusercontent.com/12057348/42093302-22a65958-7bac-11e8-88d8-1159692f88c6.png)
Windows User Administrator, Member of Group2 ProxyInternet
Log Example:
`18.06.29 14:24:02 administrator 10.21.30.21 https://www.oracle.com:443 *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste CONNECT 969213 0 - 2 200 - 10.21.30.21 ProxyInternet - - - - -`

**Test 4 - www.adobe.com**
![grafik](https://user-images.githubusercontent.com/12057348/42093320-3471e30a-7bac-11e8-864e-366b6782bf89.png)
Windows User Administrator, Member of Group2 ProxyInternet
Log Example:
`18.06.29 14:24:09 administrator 10.21.30.21 https://www.adobe.com:443 *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste CONNECT 3075 0 - 2 200 - 10.21.30.21 ProxyInternet - - - - -`

**Test 5 - www.teamviewer.com**
![grafik](https://user-images.githubusercontent.com/12057348/42093337-3fe13ede-7bac-11e8-967b-787a9988b30c.png)
Windows User Administrator, Member of Group2 ProxyInternet
Log Example:
```
18.06.29 14:31:46 - 10.21.30.21 http://www.teamviewer.com *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste GET 183 0 - 1 301 - 10.21.30.21 Default-Group - - - - -
18.06.29 14:31:46 - 10.21.30.21 https://www.teamviewer.com *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste GET 0 0 - 1 302 - 10.21.30.21 Default-Group - - - - -
18.06.29 14:31:46 - 10.21.30.21 https://www.teamviewer.com/de/ *VERTRAUENSWÜRDIG* Übereinstimmung mit Seite in Ausnahmeliste GET 72960 0 - 1 200 text/html 10.21.30.21 Default-Group - - - - -
```

Two Problems are shown here:
Several HTTPS sites are checked against DefaultGroup1, altough User is in Group2
Although we see an Exception logged, the cert comes from the fake CA. eset.com is in the exceptionlist from Group1&2

**Comment by fredbcode** [comment] 2018-06-29 13:27
Yes something is wrong here, are you using Ntlm ? Can you make a try without ?

Can you remove temporary certificate in Firefox: Tools > Clear Private Data and only put a checkmark before Authenticated Sessions -> Clear Now
And do the same in e2guardian, remove all files in temporary certs and restart, please

**Comment by xenadmin** [comment] 2018-06-29 13:46
Yes. But as this is a production environment, deactivating is no good idea. And even if I would deactivate it, I would need an alternative authentication method, because otherwise I wouldn't have a group assignment, would I?
```
auth_param ntlm program /usr/bin/ntlm_auth --helper-protocol=squid-2.5-ntlmssp
auth_param ntlm children 30 startup=0 idle=1
auth_param ntlm keep_alive off
```
The tests I sent to you, were Internet Explorer 11. Should I do some tests with Firefox portable?
About the temp cert, do you mean the following path?
`generatedcertpath = '/etc/e2guardian/ssl/generatedcerts/'`

**Comment by fredbcode** [comment] 2018-06-29 13:58
> Yes. But as this is a production environment, deactivating is no good 
> idea. And even if I would deactivate it, I would need an alternative 
> authentication method, because otherwise I wouldn't have a group 
> assignment, would I?
>


Yes group1, but it's just a short test to be sure this not related with NTLM

> ||
>
> The tests I sent to you, were Internet Explorer 11. Should I do some 
> tests with Firefox portable?
>

Yes

> About the temp cert, do you mean the following path?
> |generatedcertpath = '/etc/e2guardian/ssl/generatedcerts/'|
>
>

Yes please

**Comment by fredbcode** [comment] 2018-07-06 06:27
Some news ?

**Closed as completed** 2018-08-22 12:15 UTC
