### ISSUE TITLE
refererexceptionsitelist not working

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#493] opened 2019-01-10 06:08 UTC
How I should use it? I added search.skydns.ru, checked on https://www.whatismyreferer.com/ that it's refered, but still, I can't access any website. I have blanked block turned on.

e2guardian 5.2.2

Built with:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--enable-clamav=yes' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--enable-sslmitm=yes' '--enable-pcre=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'build_alias=x86_64-linux-gnu' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/e2guardian-MhDA5z/e2guardian-5.2.2=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/e2guardian-MhDA5z/e2guardian-5.2.2=. -fstack-protector-strong -Wformat -Werror=format-security'

**Comment by fredbcode** [comment] 2019-03-26 09:41
Still present ?

**Comment by dkwiebe** [comment] 2019-12-27 22:21
We've run into this as well on E2Guardian 5.3.3.  I'd be glad to sponsor this fix if you're interested.

e2guardian 5.3.3

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'

**Comment by GildedHonour** [comment] 2019-12-29 04:01
@dkwiebe I'd work on this issue. I'll need to get familiar with the project first.

**Comment by philipianpearce** [comment] 2020-01-06 12:16
Fixed in v5.3.dev and v5.4.dev

Note this a storyboard correction.

Previous v5 versions might be fixed without re-compiling by adding the following code to the end of the function(exceptioncheck) in common.story:-

if(refererin,refererexception) return setexception
ifnot(urlin,embededreferer) return false
if(embeddedin,refererexception) return setexception

**Comment by philipianpearce** [comment] 2020-01-06 12:23
Sorry for delay, in fixing this.  I seem to have had a blind spot on this. Once I had noticed that the referexception group of lists where not referenced in the storyboard, it was simple to fix.

I will add a log warning when defined lists are not used (v5.4.dev)- this would have made the cause of this bug obvious!  See #566

**Comment by dkwiebe** [comment] 2020-01-06 15:50
Thanks @philippearce.  Is there some way I can send you a small donation as a way of saying thanks?

**Comment by dkwiebe** [comment] 2020-03-07 23:47
This has been working for us with the configuration changes you mentioned.  Thanks for taking care of it.

**Closed as completed** 2020-08-14 20:39 UTC
Labels: bug, fixed
