### ISSUE TITLE
e2guardian slow navigation (300+ users).

### ISSUE THREAD

**Issue by fcruzcoelho** [e2guardian/e2guardian#172] opened 2017-02-02 00:25 UTC
Good evening,

Today I migrated my webfilter e2guardian to production where it was working perfect until from scratch began to slow to navigate the pages, needing to be restarted several times.

Before turning to production I ran several tests and it was working normally with more than 100 users connected simultaneously.

Follow my maxchildrens settings:
maxchildren = 6000
minchildren = 64
minsparechildren = 15
preforkchildren = 20
maxsparechildren = 80
maxagechildren = 10000

I did an analysis on my operating system:
I/O
Network
Memory
CPU
I am using virtualized server in hyper -V with the following configuration.
6 CPU
8GB Memory
Hard Disk dedicated

I found no anomaly to identify slowness.
Could you help me in any further analysis my environment has about 3000 simultaneous users from different locations.

Thank you

**Comment by fredbcode** [comment] 2017-02-02 07:40
Hello,

Here no problem with 5000 users, which version are you using ?
Maybe you have not enough memory or/and cpu ?

Fred

**Comment by fredbcode** [comment] 2017-02-02 07:41
swap ?

**Comment by fcruzcoelho** [comment] 2017-02-02 10:52
@fredbcode 

Good Morning,
My memory and CPU consumption is apparently nomal, and the same is not doing swap.
![snapshot100](https://cloud.githubusercontent.com/assets/13903548/22546421/2685b1d4-e924-11e6-8063-cb37940208c8.png)

Could you tell your settings to your 5000 users?
My version is:
![snapshot101](https://cloud.githubusercontent.com/assets/13903548/22546458/48775e14-e924-11e6-891d-c8b8b07bc57e.png)

At that moment the navigation is normal but not all my users have arrived in the company.

The same is with a total of processes within the expected for my 300 users.
![snapshot102](https://cloud.githubusercontent.com/assets/13903548/22546570/c9697f2a-e924-11e6-8cae-b39e26e8c1fe.png)

Thank you.

**Comment by fredbcode** [comment] 2017-02-02 11:42
Can you make a try without e2guardian ? I mean squid only

**Comment by fcruzcoelho** [comment] 2017-02-02 12:07
I did this test yesterday, and the squid-only navigation was normal.

I do not know if the problem happened after I made a change in the file "bannedregexpurllist" in searches on the google enconium forum where the staff was complaining that when I changed this file it started slowing down because the regex could be wrong

Yesterday I returned the backup, I am monitoring and until the moment is not being slow.

If the regex is wrong, could it cause the slowness?

Thank you.

**Comment by fredbcode** [comment] 2017-02-02 12:15
> 
> I did this test yesterday, and the squid-only navigation was normal.
> 

Ok

> I do not know if the problem happened after I made a change in the
> file "bannedregexpurllist" in searches on the google enconium forum
> where the staff was complaining that when I changed this file it
> started slowing down because the regex could be wrong
> 
> Yesterday I returned the backup, I am monitoring and until the moment
> is not being slow.
> 
> If the regex is wrong, could it cause the slowness?


Yes it can, eg it matches all domains 

Do you have some informations in syslog ?

**Comment by fcruzcoelho** [comment] 2017-02-02 12:22
I had not attacked the syslog, looking now I am having the following message.

Follow print:
![snapshot103](https://cloud.githubusercontent.com/assets/13903548/22549212/579ac022-e931-11e6-89c8-67657fcfa6b4.png)


Thank you.

**Comment by fredbcode** [comment] 2017-02-02 12:54
Sorry I don't know, maybe you should tuning your sysctl.conf ?
E2 and Squid are connected via 127.0.0.1 ?

As the problem is not related with E2  I will close this ticket, but you can try to open a discussion here: 
https://groups.google.com/forum/#!forum/e2guardian

Thanks

**Comment by fcruzcoelho** [comment] 2017-02-02 13:05
Thanks you,
I have already tuned my sysctl.conf, I am monitoring if the same lap is slow.

Yes my E2g and Squid are via 127.0.0.1.

**Comment by fredbcode** [comment] 2017-02-02 13:07
Ok, FI 3.5.0 is out https://github.com/e2guardian/e2guardian/releases/tag/v3.5.0

**Closed by fredbcode** 2017-02-02 13:07 UTC
