### ISSUE TITLE
v5: loop detection

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#523] opened 2019-04-01 16:26 UTC
Routine required to enable loop detection - a specially crafted url request can in some circumstances cause a loop eating up all httpworkers and requiring an e2g restart to clear.

Temporary workround is to ban access from localhost (and from upstream squid if used) to e2g filter (proxy and transparent) ports using firewalling on the server running e2g.   Note: This does not affect ICAP mode or HTTPS transparent port, so ICAP port should not be blocked to squid.

**Comment by Dalacor** [comment] 2019-04-01 17:26
Is there any log etc that indicates what caused the loop so I can track down the phone, website or whatever is causing the problem.

**Comment by philipianpearce** [comment] 2019-04-02 09:29
Unfortunately, not currently.  Logging is performed after a request has completed so the looping prevents the request being logged.
The loop detection code will prevent loops, deny the request, and log this with a suitable message so you will then be able to see who/what is making the call.

**Comment by Dalacor** [comment] 2019-04-02 09:45
Would you be able to include the loop detection code in the next update. Then I can install that to find out what is causing this problem. It would perhaps help other users who may have similar issues with say Whatsapp etc causing problems. Thank you. Much appreciated.

**Comment by philipianpearce** [comment] 2019-04-02 16:07
@Dalacor I have push a temporary branch called 'loopdetect'.   If you are able to test that would be great.  Once we are happy I will merge with 5.3 branch and dev branches.
Note that there is a new message (212) and that to activate you will need to add the IPs of your e2g server as checkip values to e2guardian.conf (details in file).
Regards
Philip

**Comment by Dalacor** [comment] 2019-04-02 18:04
Thank you. I will update this update if I have the problem again. I want to first see if whitelisting the mail sever webmail or the update to 5.3.2 fixes this issue before making any more changes. It has been running the last couple of days with no issues, but I need to give it two weeks as the problem is so intermittent.

**Comment by Dalacor** [comment] 2019-04-09 16:10
So far the problem has not resurfaced since updating to E2g 5.2.2 or whitelisting the webmail site. Will run E2g 5.2.2 in for around 8 weeks. If no issues, then will remove webmail from whitelist and see if problem returns. If issue is E2g 5.3.1 (and is fixed in E2g 5.2.2) do you want me to revert back to E2g 5.3.1 and install this patch or can you detect from E2g 5.2.2 changelog what the problem was?

**Comment by philipianpearce** [comment] 2019-04-09 17:20
The potential recursive loop problem is present in all v5 versions, and likely in previous versions also.

To test you need to pull the loopdetect branch and compile that.

It is very easy using a browser to replicate the symptoms you had.  I do not want to publish this on the forum for obvious reasons.  However, if you look the text I have redacted on your posts it will be fairly obvious!

**Comment by Dalacor** [comment] 2019-04-09 18:02
Sorry, I should perhaps be more clear. I understand that there is a loop issue that has as yet to be fixed and I can replicate it manually. The loop however is the end result of the problem. It's not clear what website/phone app etc is causing the loop.

So I can revert to the previous version of E2guardian to find out what was causing the loop as it may be something that needs to be fixed?  I will do that, as I would like to find out what actually caused the loop.

**Comment by philipianpearce** [comment] 2019-04-10 07:28
Yes, I understand that you want to find out what is causing the loop.  But reverting to a previous version is not likely to help, as the information you need will not be logged by e2g.

With the loopdetect branch, set up correctly, the potential loop call will be blocked and logged (with e2g message 212) making it much easier to find what has caused the loop.

**Comment by Dalacor** [comment] 2019-04-17 12:03
Sorry you are right. I forgot that the previous version does not log the cause so reverting would not help. However it would determine whether the issue is specific to E2g 5.3.1 version. So far the issue has not resurfaced. So I can only conclude that one of five things have fixed the issue as these are the only things that have changed.

1. whitelisting the email website (which I think is the cause and will test this as I think Edge and this site is the cause of the problem)
2. dropping httpworkers from 5000 to 1000 (Could be some memory related issues?)
3. upgrading to E2G 5.3.2 from E2G 5.3.1 (Possible, but unlikely)
4. reducing Linux hard limit from 18000 to 3000 (Could be some memory related issues?)
5. reducing Linux soft limit from 12000 to 2500 (Could be some memory related issues?)

When school re-opens (as its holidays now), I will run the system for another four weeks and if no issues, will remove email website from whitelist and see if issue returns as I don't believe any of the other changes could be the cause otherwise other people would have the issue. If it does return, I will then test the loop update and see if this works. Thanks

**Comment by fredbcode** [comment] 2019-06-04 07:48
Hello all, some news about this ?

**Comment by philipianpearce** [comment] 2019-06-04 08:29
loopdetect branch was merged into v5.3 and v5.3.dev some weeks ago (sorry forgot to put issue reference in commit).    We have tested and it works.

Note that to activate checkip lines need to be added to e2guardian.conf, one for each ip the e2guardian system is listening on, including VIP if used.

**Closed as completed** 2019-06-04 08:30 UTC
Labels: enhancement, fixed
