### ISSUE TITLE
Whitelists problem

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#183] opened 2017-03-07 04:47 UTC
I have a quite strange problem.
I have Debian GNU/Linux 9 (stretch), squid 3.5.23 and e2guardian 3.5.1.
On 3.4.0.3 if you had a website in blacklist - you could add it in a whitelist and this website will open. This has worked with third-level domains too, but not now.
I added some screenshots for better understanding.
![default](https://cloud.githubusercontent.com/assets/4517038/23642205/ac397d78-031a-11e7-8b31-05e82eb02f40.PNG)
![2](https://cloud.githubusercontent.com/assets/4517038/23642211/b35dd810-031a-11e7-8c8e-0d6825eed133.PNG)
![3](https://cloud.githubusercontent.com/assets/4517038/23642219/bfd23726-031a-11e7-9e96-28a3c76450da.PNG)

About the last one. I can't get the website disappear from logs by whitelisting it. It opens on a whitelist-only mode, but still appears in logs. But this has worked with "osiris".
Sorry for my English. If you need more explanation - just ask.

**Comment by fredbcode** [comment] 2017-03-07 07:28
Weird, are using an authenticate plugin ?

**Comment by fredbcode** [comment] 2017-03-07 07:42
I tried with love.mail.ru no problem here 
http://love.mail.ru -> ok
http://mail.ru -> Ko
http://test.mail.ru -> Ko

What do you mean by "osiris" ?

e2guardian 3.5.1

**Comment by Kenny690** [comment] 2017-03-07 08:07
Yes. I'm using NTLM (first) and IP (second) plugins.
I have love.mail.ru and vk.com in blacklist, but when I'm adding them in whitelist (without removing them from blacklist) only vk.com is working. This thing is only related on third-level domains.

Sorry, I didn't add some important info.
"Osiris" is a computer in my LAN and this computer has some website on it. When I'm adding "osiris" in "exceptionsitelist" - the people who has whitelist-only mode can't access it. But when I'm adding "osiris" in "exceptionregexpurllist" - everything's works fine. 
But this thing's not working with domain "a30.su". As you can see in logs, I have a message that osiris:433 is a trusted by regexp "osiris". I have a30.su in exceptionsitelist, I have a30.su, ^a30\.su.* and i even tried .*a30.su.* in exceptionregexplist, but this is not working. Site is not blocked but it's not "trusted" thou.

**Comment by fredbcode** [comment] 2017-03-07 08:56
Ok thanks for the explanations. I found something, please can you make a try ?
Please complete test 
- user with identification site denied/allowed 
- user without identification site denied/allowed
- sub domain
etc ...
Thanks for your help

**Comment by Kenny690** [comment] 2017-03-07 09:35
Whoops. I've found what's happened. But I can't understand why this is happened.
Look, I've had ".mail.ru" in squid's bypass list:

acl bypass dstdomain  "/etc/squid/bypasses"
always_direct allow bypass
cache deny bypass
cache allow all
http_access allow bypass localnet

After commenting the line ".mail.ru" whitelist is started to work again, bypassing blacklist. 
But what's exactly happening? This is the logs, when I'm commenting the line:

2017.3.7 14:18:43 - 10.12.30.206 http://love.mail.ru/stat/js-error.phtml *DENIED* : love.mail.ru POST
2017.3.7 14:18:43 shugy 10.12.30.206 http://love.mail.ru/favicon.ico *TRUSTED* GET

The only difference is that all the POSTs are blocked and all GETs are trusted on the one similar website and POST didn't have a NTLM credential. But still, e2guardian can check the user by IP address.
The next log is squid's log:

1488878590.117 10.12.30.206 TCP_DENIED/407 5910 GET http://bar.love.mail.ru/jsonp/bar?
1488878590.192 10.12.30.206 TCP_MISS/200 367 GET http://bar.love.mail.ru/jsonp/bar? SC30SURGUT\\shugy
1488878590.654 10.12.30.206 TCP_DENIED/407 5823 POST http://love.mail.ru/stat/js-error.phtml

This seems normal.
Next step - removing # from #.mail.ru.
e2guardian:

2017.3.7 14:25:21 - 10.12.30.206 http://love.mail.ru/ru/my/reg.phtml *DENIED*: love.mail.ru GET

squid:

1488878788.537 10.12.30.206 TCP_MISS_ABORTED/200 GET http://love.mail.ru/ru/my/reg.phtml

Let's try to turn off NTLM check.

The result is with or without commenting the line ".mail.ru" in squid bypasses site is blocked.

**Comment by Kenny690** [comment] 2017-03-07 09:39
Anyway this looks very strange.
I have 4 groups. 1 - no access, 2 - is default, blacklist only, 3 - admins, full access, 4 - students, whitelist-only.
Shugy (user) and 10.12.30.206 are both in group 2. But reacting on exceptions in a different way. For user - the exceptionsitelist is more important than blacklist, but for IP - it's opposite.

**Comment by fredbcode** [comment] 2017-03-07 09:58
Ok please I pushed a fix please "git pull" and retry

**Comment by Kenny690** [comment] 2017-03-07 10:24
Seems like the problem with difference between user and IP is now not a problem. But now ipgroups became useless. I've put myself in group 3 (which is admin's group), but I already get a few "access denied" pages. However, exceptioniplist is working and allowing me to bypass everything.

**Comment by Kenny690** [comment] 2017-03-07 10:39
BTW, I think I need to explain why am I need NTLM and IP auths together.
The thing is - problems with some sites. Maybe it's because I'm using MITM, maybe not. In my squid.conf I have only ntlmssp and sometimes browsers answering on 407 with nothing which cause an error but after reloading everything was starting to work again. I need IP to prevent that problem. If browser is not answering on 407, than e2 just checking an IP address and opens (or not if blacklisted) the website.

I had both ntlmssp and basic, and instead of answering with error code (in cases what I wrote higher) - browser just asked user for credentials. This was working but it was a hell for a lot of employers.

**Comment by fredbcode** [comment] 2017-03-07 10:44
Ok can you retry now, I changed something

**Comment by Kenny690** [comment] 2017-03-07 10:54
Erm... Now I have messages in logs, that website is "DENIED" but I can open them. This is first. Second is - even if site is not exception and blocked - everybody can access them, Only logfile is shouting that it's denied.

**Comment by fredbcode** [comment] 2017-03-07 11:10
Now ?

**Comment by fredbcode** [comment] 2017-03-07 11:13
Oups sorry I missed something good now

**Comment by Kenny690** [comment] 2017-03-07 11:45
The same. Everything's allowed but log file says "denied". Even on trusted ip/users.

**Comment by Kenny690** [comment] 2017-03-07 12:05
Wait a minute. I found something.
If e2 read user's credentials then it brings me "access denied" page. But if it can't and trying to describe user by IP, then it shows the blocked page but giving me in log file "denied".

**Comment by fredbcode** [comment] 2017-03-07 12:15
You speak about sites in "acl bypass dstdomain "/etc/squid/bypasses" right ?
What I do to reproduce:

1 - Put a website in bypasses (so without any identification at all)
2 - Surf on this domain and I'm denied because it's not allowed (not in whiteliste for filter1 in e2guardian) 
3 - Put the website in whitelist (e2) 
4 - Surf on website because I'm allowed  

Ok good

Second test

1 - Put my IP to group3 
2 - Allow a website only to group3
3 - I can surf
4 - remove the website to group3
5 - I'm denied

Ok good

> If e2 read user's credentials then it brings me "access denied" page
If the user is not allowed it's right

>  But if it can't and trying to describe user by IP, then it shows the blocked page but giving me in log file "denied".

With my latest" push" ? You speak about a user without credential allowed or not ?
The log is wrong or the page should be blocked ?
Can you try to clear you cache ?

**Comment by fredbcode** [comment] 2017-03-07 12:26
I added basic and digest authentication:
authplugin = '/etc/e2guardian/authplugins/proxy-digest.conf'
authplugin = '/etc/e2guardian/authplugins/proxy-basic.conf'
authplugin = '/etc/e2guardian/authplugins/ip.conf'

If I refuse the pop-up and try to surf to a website not allowed for my IP, I'm denied 

2017.3.7 13:18:33 10.253.x.x 10.253.x.x http://orpi.com *DENIED* Site interdit : orpi.com GET 0 0 liste_noire 3 403 -  groupe3 Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0  - - 
2017.3.7 13:18:37 10.253.x.x 10.253.x.x http://orpi.com *DENIED* Site interdit : orpi.com GET 0 0 liste_noire 3 403 -  groupe3 Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0  - - 
2017.3.7 13:18:45 10.253.x.x 10.253.x.x http://orpi.com *DENIED* Site interdit : orpi.com GET 0 0 liste_noire 3 403 -  groupe3 Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0  - -

**Comment by Kenny690** [comment] 2017-03-07 12:35
Finally. Seems like I were testing sites that was in bypasses and in blacklist. Now everything's seems legit.
If the site in blacklist - site is blocked. - this was working earlier.
If the site in blacklist and in bypasses - site is allowed - this was working too.
If the site is a third-level domain in blacklist, but bypasses has ".site.com" line - site is allowed - this thing wasn't working. Now it's finally ok.
What is not working for now:
If the IP is in a "full-access" filter-group (3) - everything's work, but log file contains lines about that, but it shouldn't, because group 3 has groupmode=2.
I have a site a30.su in exceptionsitelist but I still getting messages in logs like this:
10.12.30.199 http://a30.su *SCANNED*  GET 4102 0  1 503 text/html
10.12.30.199 http://a30.su/favicon.ico  GET 4107 0  1 503 text/html

**Comment by fredbcode** [comment] 2017-03-07 12:44
Hum, I have 503 code here because a30.su doesn't exist in DNS

**Comment by Kenny690** [comment] 2017-03-07 12:50
Wait a minute... I'm totally confused. Here what I wanted from the begining.
We have a site mail.ru that everybody can use. I blocked part of this site by adding love.mail.ru in blacklist.
Everything was working as i expected.
Now I want to allow love.mail.ru but I don't wanna delete the entry in blacklist. I'm adding love.mail.ru in exceptionsitelist. Now this part of site is allowed and every other part of this site is allowed directly except what I've add in blacklist.

This scheme was working on 3.4.0.3

What I've had on 3.5.1:
If the site was in bypasses and the part of this website were in blacklist - then this part of site was blocked even if i had it in exceptionsitelist.
But if the site was in the blacklist and in the whitelist but not in bypasses - then the site in whitelist was allowed and e2 didn't bother about blacklist.

**Comment by Kenny690** [comment] 2017-03-07 12:50
Oh, that's because it's a local website.

**Comment by fredbcode** [comment] 2017-03-07 13:46
My tests

1 - love.mail.ru is banned 
2 - mail.ru is allowed 

I can surf to love.mail.ru, it's allowed because the full domain is in exception
No message in e2, be carreful it's depend of your configuration 

1 - mail.ru is banned
2 - love.mail.ru is allowed

I can't surf to mail.ru but ok to love.ru 

2017.3.7 14:04:58 test_user 10.253.x.x https://mail.ru:443 *DENIED* Site interdit : Le mode liste blanche (Blanket Block) est actif et ce site n`est pas dans la liste autorisée, blanche ou grise. CONNECT 0 0 - 2 403 -  groupe2 Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/51.0  - - 

> I have 4 groups. 1 - no access, 2 - is default, blacklist only, 3 - admins, full access, 4 - students, whitelist-only.

When a user works without credential at all he uses group1 you know that ?

-----------------------
So maybe there is something I misunderstand
The is the only way I know to do what you want:

1 - mail.ru in allowed site (e2) and bypass squid
2 - bannedregexwithblancketblock = on in e2
3 - In bannedregexpurllist (love.mail.ru) -> In all or just a specific group files (eg: e2guardianf1.conf)
4 - So mail.ru is allowed but love.mail.ru not

I tried right now, with IP plugin, my source IP and mail.ru is allowed in squid.conf
I put my IP to group3 and I made the operations above (steeps 1 to 4)

love.mail.ru is denied and mail.ru is allowed

I don't know how this could works otherwise, but maybe I don't understand right, can you provide a step by step way to reproduce ?

**Comment by Kenny690** [comment] 2017-03-08 10:39
That's the point. The installation of e2 changed my group1 file. 
Everything's seems to work fine now, but please leave it open for a one day. I need to check everything tomorrow when I'll be at my work, cause some testing computers are turned off now. After that I'll write another comment about my results.

**Comment by fredbcode** [comment] 2017-03-08 10:53
Of course no problem, take your time to control everything before I release 

Thanks for your help

**Comment by Kenny690** [comment] 2017-03-10 04:01
I've made a clean installation and test everything. Looks like you fixed every problem I had. Thank you. :)

**Closed** 2017-03-11 05:55 UTC
