### ISSUE TITLE
e2guardian + CNTLM 0.92.3 issue

### ISSUE THREAD

**Issue by puppetmaster** [e2guardian/e2guardian#46] opened 2014-12-16 09:01 UTC
Using e2guardian 3.0.4 and cntlm 0.92.3 authentification don't work. Using the same version of e2guardian with an older version of cntlm (0.35) works fine. 

I'm debugging and looking for more informations if somebody have any idea please let me know.

(PS: Same problem with dansguardian)

**Comment by puppetmaster** [comment] 2015-01-09 08:20
We have more informations about this, can we re-open this issue ?

**Comment by fredbcode** [comment] 2015-01-09 08:43
Of course yes

**Comment by fredbcode** [comment] 2015-01-09 10:06
Maybe I'm misunderstanding, but:

*The problem is that CNTLM force authentification even if destination web site didn't need authentification.*

There is a big difference between this two headers

**Proxy-Authorization: NTLM** : 
Only between CNTLM -> e2guardian -> squid
It's needed with CNTLM through E2, this is proxy authorisation and should be permanently.
And
**Authorization: NTLM** : Website with and NTLM authentication:  
browser -> CNTLM -> e2guardian -> squid -> website (NTLM ident only for a specific website) 

As you can see this not the same HTTP header

CNTLM should reads NTLM **Proxy-Authorization: NTLM** authentication because this is his job.

*I think e2guardian should access non authenticate connexion even if an NTLM authentification is started and not terminated.*

E2guardian takes care only about **proxy** authentication, a complete and permanent NTLM proxy identification is needed otherwise this is a security breach, sorry but we can't allow that.

Your config above-mentioned:
browser -> CNTLM -> e2guardian -> squid -> net

In your case E2 takes only care about the identification (Proxy-Authorization:) configured in Squid 
So NTLM, after that CNTLM transform that to BASIC **proxy** and send 

Proxy-Authorization: BASIC for each requests

FYI: Website with NTLM identification should doesn't works through web proxy - in usual case -    because NTLM mean NT LAN Manager, however Squid can uses ConnPin for this http://wiki.squid-cache.org/Features/ConnPin this could be useful in local network.

And I don't know if NTLM website can pass through E2, but Microsoft no longer support NTLM in applications.

**Comment by GnunuX** [comment] 2015-01-09 15:28
Maybe it will be more clear with PCAP file (I send it with png extension because pcap file are not allowed).

Here is 2 PCAP file with this architecture: cntlm (port 3127) > e2guardian (port 3128) > squid (port 8080)

My wgetrc file:

------
http_proxy = http://10.2.3.1:3127/
proxy_user = admin
proxy_password = eole
use_proxy = on
-------

wget command: wget http://www.monip.org -O /dev/null -t 1


My default squid configuration:

-----------------------------
auth_param ntlm program /usr/lib/squid3/ntlm_smb_lm_auth -a  rah/pouet
auth_param ntlm children 20
auth_param basic children 20
auth_param basic realm Squid proxy-caching web server
auth_param basic credentialsttl 2 hours
auth_param basic casesensitive off
acl password proxy_auth REQUIRED
http_access allow noauth
-----------------------

All work fine without CNTLM.

In first case, www.monip.org is not in noauth ACL (![authentif](https://cloud.githubusercontent.com/assets/150240/5681840/28771ab0-981c-11e4-9e90-ad5716ed0daf.png)):

Frame 1 to 5: basic authentification to CNTLM
Frame 6 to 19: NTLM challenge from CNTLM to squid (via e2guardian)
Frame 20 to 24: authentif OK, squid download web page
Frame 25 to 30: squid send page to e2guardian
Frame 31 to 35: page send to CNTLM

If I add www.monip.org to my noauth ACL in squid (![noauthentif](https://cloud.githubusercontent.com/assets/150240/5681843/2e423d76-981c-11e4-9263-9d782069f38b.png):

Frame 1 to 5: basic authentification to CNTLM
Frame 6 to 10: cntlm start challenge from CNTLM to squid (via e2guardian)
Frame 11 to 17: not authenfication needed for squid, download web page
Frame 18: e2guardian recieve webpage but are not unable to send it to cntlm

e2guardian is not unable to send my webpage.

**Comment by fredbcode** [comment] 2015-01-10 17:00
Ah, c'est beaucoup plus clair maintenant :)

I will take a look next week, where I can see the pcap file ?
What do you think about switch e2 with CNTLM, like this:

browser -> e2guardian -> cntlm -> squid -> net

And I guess this should reduce the load for e2 because BASIC ident code is more simpler

**Comment by GnunuX** [comment] 2015-01-10 17:56
First one: https://cloud.githubusercontent.com/assets/150240/5681840/28771ab0-981c-11e4-9e90-ad5716ed0daf.png
Second one: https://cloud.githubusercontent.com/assets/150240/5681843/2e423d76-981c-11e4-9263-9d782069f38b.png
(those file arn't png file)

*What do you think about switch e2 with CNTLM*

No, because CNTLM is use only for a set of computer (mainly mobile workstation integrated to an other windows domain).

**Comment by fredbcode** [comment] 2015-01-10 18:42
I watched quickly (sorry very quickly) 

If I understand right the packet 18 is a FIN, ACK from e2 to CNTLM, so where is the communication between Squid and e2 ? We don't know why E2 close this cnx

Same thing to the other trace packet 24,25,25 are answer from port 3128 to randomly source port (42952 in this case) so I guess the answer from e2 to CNTLM , but nothing for squid to e2

**Comment by fredbcode** [comment] 2015-01-10 19:13
Oh I forgot, in trace - normally - without identification, why there is a NTLM negotiation (packet 9) ?
As I said e2guardian can't do that because it just relay packet without any change at all.

But in this case there is a NTLM negociation:
Proxy-Authorization: NTLM TlRMTVNTUAABAAAABrIAAAMAAwAkAAAABAAEACAAAABBTU9OUkFI\r\n

If the problem is CNTLM is buggy and force NTLM identification, unfortunately we can't change that with e2. This is too dangerous for security 

The squid answer should be very interesting ...
I can suppose that there is a second negotiation without identification for each packet, this is also a performance issue ...
And E2/DG breaks this weird dialog

**Comment by GnunuX** [comment] 2015-01-12 11:03
![authentif](https://cloud.githubusercontent.com/assets/150240/5701900/99e065b6-9a52-11e4-8bd2-9a678fe72b23.png)
![noauthentif](https://cloud.githubusercontent.com/assets/150240/5701901/9d96201a-9a52-11e4-8d15-5cb1278f5fc2.png)

Sorry, i forgot port 8080 in my tshark filter. Here are new captures:

https://cloud.githubusercontent.com/assets/150240/5701900/99e065b6-9a52-11e4-8bd2-9a678fe72b23.png
https://cloud.githubusercontent.com/assets/150240/5701901/9d96201a-9a52-11e4-8d15-5cb1278f5fc2.png

**Comment by fredbcode** [comment] 2015-01-12 12:25
Ok the problem is that CNTLM try to negotiate with Squid a NTLM when this is not needed 

Proxy identification works like this:

1) The user makes a request
2) Squid returns a 407 status code, along with an header: Proxy-Authenticate: NTLM
3) The client connects and issues a GET-request, this time with an accompanying
Proxy-Authorization: NTLM
4) The server once again replies with a 407 ("proxy auth required") status code, along with an header:Proxy-Authenticate: NTLM still_some_more_stuff
5) The client sends a new GET-request, along with an header: Proxy-Authenticate: NTLM cmon_we_are_almost_done
6)  Either the server denies the authentication via a 407 return code, and we're back to square one, or it returns the requested resource.
From now on, until the TCP connection will be kept alive, no further credentials will be sent from the client to the proxy . The TCP connection is marked as "OK", and the client expects that it can pump whatever it wants. Honestly, it can't get much dumber than this. 

Your problem is that the "client" uses a NTLM secure identification.

E2 waits the NTLM Message Type: NTLMSSP_CHALLENGE but it never come.
I also guess the packet 13 should be not returned by squid (bug ?) because it answer without identification HEADER at a request who needs an identification (from CNTLM point of view of course) 

Can you make a trace with CNTLM 0.35 to see the difference ? Just with noauth acl

Also can you try this, in authplugins/proxy-digest.conf add noauthdomains = '/yourpath/test/' and add your domain in test file

**Comment by GnunuX** [comment] 2015-01-19 13:47
> Can you make a trace with CNTLM 0.35 to see the difference ? Just with noauth acl

In fact, we have quite same problem with cNTLM 0.35. In this version, ntlm authentification are only tried one time. Se we have an error, we just have to refresh page to access to the website.

> Also can you try this, in authplugins/proxy-digest.conf add noauthdomains = '/yourpath/test/' and add your domain in test file

No difference with this configuration.

**Comment by fredbcode** [comment] 2015-01-19 14:19
OK, unfortunately I see no answer with e2 for this problem.
Change the CNTLM code or your architecture seems the only way. At worst maybe you can also change the E2 code but it's should be hard to maintain after (3.3.0 is in approach)

Personally, I'm using simultaneous auth methods (ACL) with squid, for example wget negotiates BASIC identification automatically (transparent for user), recent browser DIGEST, and for some others no AUTH at all.

**Comment by GnunuX** [comment] 2015-01-19 14:25
I understand, thanks for your help.

**Closed** 2015-02-24 09:02 UTC
Labels: bug
