### ISSUE TITLE
traffic from parent proxy in sandwich mode, does not log client with mitm=on

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#241] opened 2017-06-20 17:20 UTC
I guess some ismitm test is missing x-forward-for options and logging proxy ip instead of client ip.

Same client log:
2017.6.20 12:47:26 lab 127.0.0.1 https://www.google.com.br/ ...
2017.6.20 12:44:15 lab 172.17.20.45 http://detectportal.firefox.com/success.txt ......

without mitm
2017.6.20 14:25:56 lab 172.17.20.45 https://analysis.infoglobo.com.br:443 - CONNECT

**Comment by fredbcode** [comment] 2017-06-20 17:23
What do you mean exactly by sandwich ?

**Comment by marcelloc** [comment] 2017-06-20 17:26
squid -> e2guardian -> squid

**Comment by fredbcode** [comment] 2017-06-20 17:38
It works with squid -> squid ?
Do you see the right address in the second ?

Le 20 juin 2017 19:26:19 GMT+02:00, Marcello Coutinho <notifications@github.com> a écrit :
>squid -> e2guardian -> squid
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/241#issuecomment-309829751

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by marcelloc** [comment] 2017-06-20 18:34
I'm using x-forward to log user ip.
On squid I set forwarded_for on 
and on e2guardian I set XForwarded for filter ip ,forwardedfor and usexforwardfor
this way I get client ip addresses on log, but not on ssl sites while using mitm

**Comment by fredbcode** [comment] 2017-06-21 07:15
Hum certainly a bug with usexforwarededfor because I have no problem here with SSLMITM and e2 + squid.
Did you make a try with xforwardedforfilterip commented ?

**Comment by fredbcode** [comment] 2017-06-22 09:02
Not related with SSLMITM, 
checkheader in HTTPHeader.cpp doesn't catch 'X-Forwarded-for' from client in SSL situation

Can you confirm that you have the same issue with enablessl = off ?

**Comment by marcelloc** [comment] 2017-06-22 11:17
With mitm=off and enablessl=on works. I'll test with both off

**Comment by fredbcode** [comment] 2017-06-22 14:15
I saw a potential bug, can you make a try with the branch "develop"

**Comment by marcelloc** [comment] 2017-06-23 00:13
Tried current devel branch but I guess the x-forward is being cleaned or added a second header line with 127.0.0.1 during MITM process

2017.6.22 21:09:42 lab 172.17.26.3 http://detectportal.firefox.com/success.txt - GET 8 0 - 1 200 text/plain - Default - - - - -
2017.6.22 21:09:42 lab 127.0.0.1 https://usermatch.krxd.net/um/v2?partner=google

**Comment by fredbcode** [comment] 2017-06-23 06:53
For the record:
In this case Header is added line 1709 in ConnectionHandler.cpp 
It works well with xforwaded_for but not with getxforwarded_for because pxforwardedforip is empty

Marcelloc can try something easy 

https://github.com/e2guardian/e2guardian/blob/develop/src/ConnectionHandler.cpp#L1709
Line 1703, can you switch the code like fix
```

                    if (o.forwarded_for){
                        std::string xforwardip(header.getXForwardedForIP());
                        if (xforwardip.length() > 6)
                            header.addXForwardedFor(xforwardip);
  
```
```
                    if (o.forwarded_for){
                        std::string xforwardip(header.getXForwardedForIP());
                        header.addXForwardedFor("10.1.1.1");
```

An tell me if now you have 

2017.6.22 21:09:42 lab **10.1.1.1** https://usermatch.krxd.net/um/v2?partner=google

**Comment by fredbcode** [comment] 2017-06-23 08:21
OK I added and tested a fix, works well here 

Squid(a) -> e2guardian -> Squid(b) (Auth digest)

In Squid (b) 127.0.0.1 is now removed and I can see the users addresses

In A:

Squid.conf

```
forwarded_for on
follow_x_forwarded_for allow all

```

E2Guardian:
```
forwardedfor = on
usexforwardedfor = on
# "usexforwardedfor" option enabled, you may want to specify the IPs from which
# xforwardedforfilterip line.
# xforwardedforfilterip =  

```
Squid(B)

```
forwarded_for on
follow_x_forwarded_for allow all
```

**Comment by marcelloc** [comment] 2017-06-24 04:39
Tried with latest code, but e2guardian logs still shows 127.0.0.1

I'm using squid A with basic auth
e2g with forwardedfor = on, usexforwardedfor = on
squid B no auth

2017.6.24 1:36:38 lab 172.17.26.4 http://horizon.globo.com/auth-session/
2017.6.24 1:36:38 lab 127.0.0.1 https://px.moatads.com

**Comment by marcelloc** [comment] 2017-06-24 04:55
Also looks like e2guardian in squid log format does not shows any ip, just user in ipauth

1498279972.585     32 - TCP_MISS/200 8 GET http://detectportal.firefox.com/success.txt 172.17.26.4 DEFAULT_PARENT/127.0.0.1 text/plain
1498279973.241    204 - TCP_MISS/200 43 GET https://smetrics.uol.com.br/b/ss/uoluoldevtest 172.17.26.4 DEFAULT_PARENT/127.0.0.1 image/gif

**Comment by fredbcode** [comment] 2017-07-07 07:57
I can't reproduce here, some news ?

**Comment by fredbcode** [comment] 2017-10-11 07:22
Closing this for now, please feel free to reopen if any updates

**Closed by fredbcode** 2017-10-11 07:22 UTC
