### ISSUE TITLE
Trouble with IP authentication in 5.4

### ISSUE THREAD

**Issue by jwc866** [e2guardian/e2guardian#599] opened 2020-04-24 21:34 UTC
Hello: 
I recently upgraded to 5.4 from 5.3.1 on Raspian, and merged the config from 5.3.1 to 5.4 (I used default 5.4 config files and added my custom entries to them).  Currently using the package here: http://e2guardian.traceroot.fr/v5.4.dev/e2raspbian_buster_v5.4.dev_20200407.deb

Everything seems to be working fine except that I was using IP authentication and now it is no longer identifying the user based on their IP.  I see that 5.4 reworked authentication to storyboard files and have been looking to see why it is not working.  I have confirmed that:

1) This is uncommented in /etc/e2guardian/e2guardian.conf:  
ipmaplist = 'name=ipmap, path=/etc/e2guardian/lists/authplugins/ipgroups'
2) I used the same IP groups I had before, and they are in the file /etc/e2guardian/lists/authplugins/ipgroups
3) I disabled other authentication types (I'm only using IP authentication)
4) Filter group configuration files are in tact as /etc/e2guardian/e2guardianf1.conf, f2, etc.
5) filtergroups = 3 set correctly in /etc/e2guardian/e2guardian.conf
6) In the logs, it is seeing the IPs of the client computers so it definitely seems an issue with the IP authentication

But in the logs all users are being defaulted to access group 1 and not identified.

Is there anything else in 5.4 that may have changed the IP authentication?  Or anything else I can check?

Thank you very much.

**Comment by philipianpearce** [comment] 2020-04-27 07:58
Check your pre-auth.story file has the required 'auth_ip' function and that the authplugins/ip.conf file has the line story_function = 'auth_ip' present. 

Also, look for any warnings on stdout and in syslog when e2g starts. 

Philip 

----- Original Message -----

**Comment by jwc866** [comment] 2020-04-27 12:36
> Check your pre-auth.story file has the required 'auth_ip' function and that the authplugins/ip.conf file has the line story_function = 'auth_ip' present. Also, look for any warnings on stdout and in syslog when e2g starts.

Thank you for the reply.

1) I have checked, in /etc/e2guardian/preauth.story, the lines are uncommented:
function(auth_ip)
if(clientin,ipmap) return setgroup

2) The file /etc/e2guardian/authplugins/ip.conf was missing so I copied from the "configs" folder, and ensured this is uncommented:

story_function = 'auth_ip'

Even though, in /etc/e2guardian/e2guardian.conf, it has these lines by default:

##NEWIN V5.4
#Note that from v5.4 lists used by auth plugins are defined here and not in auth *.conf files
[SNIP]
#authplugin = '/etc/e2guardian/authplugins/ip.conf'
ipmaplist = 'name=ipmap, path=/etc/e2guardian/lists/authplugins/ipgroups'

However I uncommented the line above for "authplugin =  "... , however the same result.

3) I have checked stdout and syslog when the service starts, this is all that is reported:

Apr 27 08:25:27 myserver e2guardian[13044]: SB warning: Undefined list /etc/e2guardian/e2guardianf1.story list nolog used at line 285 of /etc/e2guardian/common.story
Apr 27 08:25:27 myserver e2guardian[13044]: SB warning: Defined list regexpreplacelist:redirect is not referenced in the storyboard /etc/e2guardian/e2guardianf1.story
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag End Hour over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag Days over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag End Hour over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag Days over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag End Hour over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag Days over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag End Hour over bounds.
Apr 27 08:25:27 myserver e2guardian[13044]: Time Tag Days over bounds.

I am trying to use the time functions, and not yet sure of the "over bound" errors, but they are unrelated to the IP authentication.

Thanks again for your help.  I will also keep looking for a possible solution here.

**Comment by philipianpearce** [comment] 2020-05-25 13:45
As you have discovered you still need to activate your auth plug-in with authplugin =  ..../ip.conf.
The comment only applies to the lists which were previously defined in ip.conf but are now defined in e2guardian.conf.  Sorry that that was not clear - I've now rewritten/moved these in the example config in v5.4.dev to make this clearer.

Have you got it working as you want yet? - the 'over bounds' errors mean that the fields had more than 24hrs, 60min etc

**Comment by ccoager** [comment] 2020-07-08 01:18
I can confirm this bug as well.  Tried putting my machine into a specific filter group and it always came up as the default group.  I downgraded to 5.3.4 and it is working as expected again.

**Comment by philipianpearce** [comment] 2020-07-13 11:37
I have now managed to replicate this - will fix.

**Comment by philipianpearce** [comment] 2020-07-13 12:06
I  can only replicate this if I have the filtergroups set to 1.   When set to the correct number of filter group all works OK.

**Comment by ccoager** [comment] 2020-07-13 14:16
My filtergroups is set correctly to 2 and the issue is still reproducible.

**Comment by philipianpearce** [comment] 2020-07-13 14:33
If you would send me a copy of these config files:- pre-auth.story, e2guardian.conf, and authplugins/ipgroups, I will try and reproduce with your configs. 

Regards 
Philip 

----- Original Message -----

**Comment by ccoager** [comment] 2020-07-14 01:45
Try this.  I'm using this with squid with e2guardian in ICAP mode.
[599.zip](https://github.com/e2guardian/e2guardian/files/4916032/599.zip)

`Jul 13 21:26:09 proxy-e2guardian 06e1e09833df[19353]: 1594689969.977            -       192.168.0.50    192.168.0.50    https://www.google.com:443      CONNECT 0       0       -       Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0  -       1       -       0       -       0       -   default  1       -       1344:IS::`

**Comment by philipianpearce** [comment] 2020-07-14 08:19
I think this is a different issue to jwc866 so have open a new issue for this. #616

**Comment by Dalacor** [comment] 2020-08-14 09:40
I don't know if my problem is related as nobody mentions an error message and I am trying to get port authentication to work, not IP authentication. Had no issues getting this to work in ver 5.3

Using a default install of 5.4, I have added the following in e2guardian.conf:

filterports =8080
filterports =8081
filterports =8082
filterports =8083

filtergroups = 4

enabled authplugin - port.conf (not sure if I needed to add this or not as this is supposed to be backwards compatible)
enabled maplist portgroups
disabled ipmaplist as not using ip authentication

Left port.conf and preauth.story as default as they seem to have the settings that they should

portgroups file (I even tried copying the settings below to the port.conf file as I believe that e2guardian is looking for the below and not using portgroups file -  but doesn't work even in ports.conf file). So in what file do I put these settings).

8080 = filter1
8081 = filter2
8082 = filter3
8083 = filter4

I copied e2guardianf1.conf to 2, 3 and 4.

But when I restart E2guardian I keep getting this error message below:
"in MapAuthPorts Mode you need to setup one port per auth plugins" - I have mapauthtoports and mapportstoips both off as was in 5.3 version.

As everyone else using IP authentication is not mentioning this error message, I am not sure if the issue is the same cause, but I suspect it may be. I am running 5.4.1 if that helps

**Comment by philipianpearce** [comment] 2020-08-14 12:30
@Dalacor Are you using v5.4.1 or v5.4.2? If v5.4.1 please try v5.4.2 and see revised e2guardian.conf comments in v5.4.2. 

You still need to define the authplugin ...port.conf there is no change here. 

But port.conf has a revised format - copy the sample from configs/authplugins/port.conf 

The other change is that the portgroups file is no longer declared within port.conf, but as a maplist in e2guardian.conf. 

Format of lists/authplugins/portgroups file is unchanged. 

mapauthtoports issue - if this is off then you should not the be getting this message. 

If you continue to have this issue, please can you post your e2guardian.conf, preauth.story, and port.conf files? 

Thanks 
Philip 

Thanks 

Thanks 

Philip 

----- Original Message -----

**Comment by Dalacor** [comment] 2020-08-14 13:20
I am using 5.4.1. I tried installing 5.4.2 but the install does not work - it is missing nearly all the files!

I have uploaded the files so that you can confirm that I have them configured correctly. Thanks

[portauth.zip](https://github.com/e2guardian/e2guardian/files/5074757/portauth.zip)

**Comment by philipianpearce** [comment] 2020-08-14 15:20
This is what is causing the mapauthtoports issue (in e2guardian.conf) 

# to number of ports 
# on (default) | off 
#mapauthtoports = off 

It's commented out and default in v5.4.1 is 'on' (changed in v5.4.2 to off) 

All the other files are fine. 

What files are missing when you install v5.4.2r? I have tested a make install here and it works as expected and I can not see anything missing. Note that most of the contents of the sample lists directory has been moved into sub-directories (see config/lists/README), a change from v5.4.1. 

Also, that many defaults have been changed to agree with the suggested values in e2guardian[f1].conf. 

Regards 
Philip 

----- Original Message -----

**Comment by Dalacor** [comment] 2020-08-14 17:58
Aah yes - my bad. I did not read that section carefully enough and was thinking that because it was remmed out it was off, not on! I should have checked my 5.3.4 file and noticed the discrepancy.

I would recommend that E2guardian move to a format where if it is remmed out - the default is off. If it needs to be on then it should be unremmed. It would make it easier to pick up what's on/off.

With the very latest version, I do this:

./autogensh.
./configure --prefix=/usr/local/e2guardian --enable-clamd=yes --enable-email=yes --with-proxyuser=e2guardian--with-proxygroup=e2guardian--enable-sslmitm=yes

Make
Make install
Make clean

This is what I have always done and it installs without any problems on stable versions.

On this version (I am using Slackware Linux by the way), it does not install the sbin\e2guardian file or the folder for that matter, nor any of the files in e2guardian folder such as e2guardian, e2guardianf1, preauth.story etc files. There is just the lists folder. No authplugins folder etc. Many files like that missing.

Not to worry, I will wait for stable 5.4.2 as I managed to get 5.4.1 working now that I realised what I had done wrong. It's probably something that needs to be added to the install routine.

**Comment by philipianpearce** [comment] 2020-08-14 19:29
The defaults in v5.4.2 are more sensible, but I do not think that the bools all default to 'off'. We wll look at this again in v5.5.

OK, I'll close this ticket now, as it seems to be getting overloaded, with several different although similar issues.  Most of which are now resolved.

Please open new specific ticket if problems are persisting.

**Closed as completed by philipianpearce** 2020-08-14 19:29 UTC
