### ISSUE TITLE
Anydesk and some other programs using ssl does not work on pfsense when e2guardian is active

### ISSUE THREAD

**Issue by tolga-kkaya** [e2guardian/e2guardian#420] opened 2018-08-06 13:21 UTC
I use e2guardian without squid. Transparent HTTP Proxy and SSL support is open.
Anydesk works without problem when e2guardian is disabled. Anydesk does not work when e2guardian is enabled. Here is the network traffic between pfsense and pc:

[anydesk.tar.gz](https://github.com/e2guardian/e2guardian/files/2262664/anydesk.tar.gz)

I analyzed pcap files. Anydesk and other programs which they dont work with e2guardian have similar client hello packages. They don't include server_name extension in client hello package. And when i followed tcp stream, i saw on the answer, blocked url is https://127.0.0.1

**Comment by ravegen79** [comment] 2018-08-08 02:03
anydesk connects to servers of ip address format, you should allow those.

**Comment by tolga-kkaya** [comment] 2018-08-08 08:35
I think it is not a good solution to allow the ip address of all programs.

**Comment by ravegen79** [comment] 2018-08-08 09:13
You can ask that directly from anydesk

**Comment by philipianpearce** [comment] 2018-08-08 09:42
It would allow the filtering to be easily by-passed if you allowed https to any IP address. Many proxy by-pass programs use exactly this trick! 

The answer to your problem is to add the Anydesk IP(s) to the exceptionsiteiplist. 

I will close this issue as this is a configuration issue and not a bug. 

----- Original Message -----

**Closed as completed** 2018-08-08 09:43 UTC
Labels: configuration issue
