### ISSUE TITLE
Bypass e2guardian / squid auth by MAC address

### ISSUE THREAD

**Issue by waltertakashi** [e2guardian/e2guardian#186] opened 2017-03-11 16:33 UTC
Hi guys! We have some machines that belong to the directors and their PC must have no restrictions to access the Internet. When we were using only Squid, I created an "arp" rule to allow them to access directly without being prompted to enter their credentials. Now, using e2guardian, this rule seems to not work. Is there any way to bypass the Squid auth by MAC address?

Thank you!

**Comment by fredbcode** [comment] 2017-03-12 12:05
No there is no way because e2guardian mask from squid the user mac address 
You can try to open squid with another port and configure your users without e2guardian or add an account user/password for VIP (and put this credential to a specific group in E2)

As the problem is not related with a bug I will close this ticket, but you can try to open a discussion here:
https://groups.google.com/forum/#!forum/e2guardian

**Closed by fredbcode** 2017-03-12 12:05 UTC
