### ISSUE TITLE
e2guardian 3.5.0 error: NTLM - step 2 was not part of an auth handshake! 

### ISSUE THREAD

**Issue by Lupick** [e2guardian/e2guardian#178] opened 2017-02-17 16:11 UTC
Hi,
I'm using e2guardian 3.4.0.3 + squid and NTLM auth.  
I'm testing the new e2guardian 3.5.0.  I've compiled from source with the same param. that I've always used:
 #src/e2guardian -v
Running in debug mode...
e2guardian 3.5.0

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=1024' '--with-dgdebug'

but if if I try to use it I get on my /var/log/messages:

Feb 17 17:03:27 XXX e2guardian[8911]: Started successfully.
Feb 17 17:03:42 XXX e2guardian[8915]: NTLM - step 2 was not part of an auth handshake! (HTTP/1.1 301 Moved Permanently#015)
Feb 17 17:03:42 XXX e2guardian[8915]: Auth plugin returned error code: -1
Feb 17 17:05:27 XXX e2guardian[8914]: Proxy connection broken (2); trying to re-establish...
Feb 17 17:05:38 XXX e2guardian[8915]: Served 1 requests on this connection so far - ismitm=0

the config files /squid are the same of the prev. version:
### pure ntlm authentication
auth_param ntlm program /usr/bin/ntlm_auth --diagnostics --helper-protocol=squid-2.5-ntlmssp --domain=NFIMA
auth_param ntlm children 80
auth_param ntlm keep_alive off

**Comment by fredbcode** [comment] 2017-02-17 17:07
Can you provide more informations about your systems, OS, browsers, etc ?

I made some change recently can you try to reverse ? 
https://github.com/e2guardian/e2guardian/commit/ad5f8c5fcd1ca4b1eff637954a9fc968643e0e24

After that  
make clean
make

**Comment by Lupick** [comment] 2017-02-20 11:32
yes you are right.
I've reverted the code as suggested and recompiled and not it's working again.

PS in the system messages log I get:
 Served 2 requests on this connection so far - ismitm=0

several time. 

Probably because I've compiled with debug mode on?

**Comment by fredbcode** [comment] 2017-02-20 11:50
> Probably because I've compiled with debug mode on?

Yes

> I've reverted the code as suggested and recompiled and not it's working again.

Strange, no problem here with squid 3.5.23 windows 10, firefox or edge

**Comment by fredbcode** [comment] 2017-02-20 12:08
Please reverse and try again, without debug, with all systems restarted

**Comment by Lupick** [comment] 2017-02-20 15:14
I've deleted the source e2guardian folder and re-extracted the tgz. Then I've compiled from scratch e2guardian v3.5.0  withouth the debug support.

The proxy was  working but I got yet this message several times:

Feb 20 14:20:21 XXX  e2guardian[14923]: NTLM - step 2 was not part of an auth handshake! (HTTP/1.1 200 Connection established#015)
Feb 20 14:20:21 XX e2guardian[14923]: Auth plugin returned error code: -1

the client pc is windows 7 (latest patch)  and I've used Chrome v56 and IE11.

The server is a CentOS Linux release 7.3.1611
Squid Cache: Version 3.5.20

Finally I've rebooted the server. The first 5 min I didn't see any error then I got the same error messages

**Comment by fredbcode** [comment] 2017-02-20 15:17
> Finally I've rebooted the server. The first 5 min I didn't see any error then I got the same error messages

Messages, but it works ?
Ok thanks please try a moment without the latest fix and tell me the result

**Comment by Lupick** [comment] 2017-02-20 16:29
Even if I have the NTLM error message the proxy is working. It collect 2 messages every 5 sec.

I've started a new test; Now I've reverted the code in ad5f8c5 and I'm testing for some times  if no error message appear..

After 30 min looks like everyting is ok.

So something looks related to the ad5f8c5 commit

**Comment by fredbcode** [comment] 2017-02-21 10:48
Lupick can you make a try with the develop branch (3.5.0.1) 
How many simultaneous users connected ?

**Comment by Lupick** [comment] 2017-02-21 13:45
Good News. it looks like dev version 3.5.0.1 is working.

**Comment by Lupick** [comment] 2017-02-21 14:25
I've found a little issue.

If I try to connect to skype website (www.skype.com) the browser (firefox) stay in connecting. reverting to 3.4.0.3 it connect immediatly

**Comment by fredbcode** [comment] 2017-02-21 14:35
Great, I will wait a moment and close
How many users ?

**Comment by Lupick** [comment] 2017-02-21 14:40
at the moment just one!! I'm in a testing environment but I assume we will have around 10/20 concurrent user.

Please give a look to this before close the ticket:

"If I try to connect to skype website (www.skype.com) the browser (firefox) stay in connecting. reverting to 3.4.0.3 it connect immediately"

Thank you for your support!!

**Comment by fredbcode** [comment] 2017-02-21 14:46
www.skype.com works here, at least the front page

**Comment by fredbcode** [comment] 2017-02-21 14:47
FF 51.0.1 + w10

**Comment by Lupick** [comment] 2017-02-21 14:51
Tested on FF52.b07 + W10 and on a second PC W7 + FF51.0.1

**Comment by fredbcode** [comment] 2017-02-21 15:19
Do you have an account on skype.com ?

**Comment by fredbcode** [comment] 2017-02-21 15:26
I mean maybe you are already connected and me not ?

**Comment by Lupick** [comment] 2017-02-21 15:27
yep same username ;)

**Comment by fredbcode** [comment] 2017-02-21 15:29
Can you try like me deconnected (without any identity on website) ?

**Comment by Lupick** [comment] 2017-02-21 15:45
Ok on W10 + FF52.b07 . I've stopped any e2guardian services and launched:
 e2guardian.3.4  -Q -N

I can browse www.skype.com website. I'm not logged to the site (I've sign in button on the top left)

then Ive killed e2guardian and started 

e2guardian.3.5.0.1  -Q -N

I cannot access skype. same issue with IE.

**Comment by Lupick** [comment] 2017-02-22 07:11
I've made another test using v3.5.0 with the  ad5f8c5 reverted and no problem on www.skype.com

**Comment by Kenny690** [comment] 2017-03-06 08:16
Got it!
I had this problem because I had this is my squid.conf:

acl bypass dstdomain  "/etc/squid/bypasses"
always_direct allow bypass
cache deny bypass
cache allow all
http_access allow bypass localnet

After removing these lines - everything started to work. Except a few sites that giving me 403 and office365.
But this was working on e2guardian 3.4.0,3. What do I need to do now?

**Comment by fredbcode** [comment] 2017-03-06 08:35
Ok can you make a try with the latest dev branch, I guess it works now

**Comment by Kenny690** [comment] 2017-03-06 09:04
Thanks. The problem is gone now.

**Comment by fredbcode** [comment] 2017-03-06 15:24
Ok I will the weekend to release
Lupick ?

**Comment by Lupick** [comment] 2017-03-06 16:54
I still have some problem on some ssl site like skype.com:

./e2guardian -N -Q > XXX.log
No e2guardian process found.
Socket 0 fd:6
bindSingle binding port8080
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
PID: 4488 Start URL https://www.skype.comis_ssl=1ismitm=0
Auth plugin returned error code: -1
--------------------------------------------------------
[XXX.log.txt](https://github.com/e2guardian/e2guardian/files/821856/XXX.log.txt)

**Comment by Lupick** [comment] 2017-03-06 16:56
looks ok.

still have problem with https but probably due to my squid config.

**Comment by Kenny690** [comment] 2017-03-12 09:18
I'm getting it from time to time, but I can't catch it because a lot of traffic is going through e2. I'll report tomorrow about what I've found.

**Comment by fredbcode** [comment] 2017-03-12 12:00
This is not abnormal, It can be timeout, broken answer, etc
But it's still interesting to know what happen, thanks

**Comment by fredbcode** [comment] 2017-03-15 12:42
Fixed in 3.5.1

**Closed by fredbcode** 2017-03-15 12:42 UTC
